### ISSUE TITLE
Doesn't compile on ubuntu 16.04

### ISSUE THREAD

**Issue by sokoow** [xmrig/xmrig-nvidia#59]
Hey,

I got this when I try to compile on Ubuntu 16.04:

```
  6%] Built target xmrig-cuda
[  9%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o
/home/sokoow/Desktop/monero-miner/xmrig-nvidia/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/home/sokoow/Desktop/monero-miner/xmrig-nvidia/src/api/ApiState.cpp:154:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
                                                     ^
/home/sokoow/Desktop/monero-miner/xmrig-nvidia/src/api/ApiState.cpp:161:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^
/home/sokoow/Desktop/monero-miner/xmrig-nvidia/src/api/ApiState.cpp:165:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^
CMakeFiles/xmrig-nvidia.dir/build.make:86: recipe for target 'CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Help please? :)

**Comment by tyz210** [comment]
Have the same problem. Helps add old compiler by hands -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5

Delete old build folder and create new. After that use:
cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE=RELEASE path/to/sources

**Comment by sokoow** [comment]
nope, still the same

**Comment by tyz210** [comment]
Are you sure that you didn't change any source files?

**Comment by xmrig** [comment]
You need use libuv1 not libuv 0.10.
Thank you.
