### ISSUE TITLE
error in ApiState.cpp while compiling xmrig-nvidia in Ubuntu 17.10

### ISSUE THREAD

**Issue by felis** [xmrig/xmrig-nvidia#36]
Hello,

I'm attempting to compile current xmrig-nvidia master in Ubuntu 17.10 using gcc5. I'm getting the following error while compiling api/ApiState.cpp:

[ 11%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o
/home/user/work/xmrig-nvidia/src/api/ApiState.cpp: In function ‘double normalize(double)’:
/home/user/work/xmrig-nvidia/src/api/ApiState.cpp:55:10: error: ‘__builtin_isnormal’ is not a member of ‘std’
     if (!std::isnormal(d)) {
          ^
/home/user/work/xmrig-nvidia/src/api/ApiState.cpp:55:10: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnormal’

What am I doing wrong?

Cmake, make output is here->

https://gist.github.com/felis/220720cb0442a70d92a3d058d36d623d

**Comment by felis** [comment]
Compiles and works fine on 17.04 as per wiki.

**Comment by mattWhitwam** [comment]
Same issue here.

**Comment by mattWhitwam** [comment]
changed std::isnormal in ApiState.cpp to isnormal and also for 3 instances in Hashrate.cpp and it compiled successfully. testing now.

**Comment by aensley** [comment]
Same error here. I'm going to try what @mattWhitwam suggested now.

Prereqs:

```ShellSession
aensley@desktop:~/xmrig-nvidia$ sudo apt-get install git build-essential cmake libuv1-dev nvidia-cuda-dev nvidia-cuda-toolkit gcc-5 g++-5 libmicrohttpd-dev
[sudo] password for aensley: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
cmake is already the newest version (3.9.1-1).
gcc-5 is already the newest version (5.5.0-1ubuntu1).
git is already the newest version (1:2.14.1-1ubuntu4).
libuv1-dev is already the newest version (1.9.1-3).
g++-5 is already the newest version (5.5.0-1ubuntu1).
libmicrohttpd-dev is already the newest version (0.9.55-1).
nvidia-cuda-dev is already the newest version (8.0.61-1).
nvidia-cuda-toolkit is already the newest version (8.0.61-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
aensley@desktop:~/xmrig-nvidia$ mkdir build
aensley@desktop:~/xmrig-nvidia$ cd build
```

Config:

```ShellSession
aensley@desktop:~/xmrig-nvidia/build$ cmake .. -DCUDA_ARCH=30 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found suitable version "8.0", minimum required is "7.5") 
-- Found NVML: /usr/include  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aensley/xmrig-nvidia/build
```

Build:

```ShellSession
aensley@desktop:~/xmrig-nvidia/build$ make
[  2%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.o
[  4%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_core.cu.o
Scanning dependencies of target xmrig-cuda
[  6%] Linking CXX static library libxmrig-cuda.a
[  6%] Built target xmrig-cuda
Scanning dependencies of target xmrig-nvidia
[  9%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/Api.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o
/home/aensley/xmrig-nvidia/src/api/ApiState.cpp: In function ‘double normalize(double)’:
/home/aensley/xmrig-nvidia/src/api/ApiState.cpp:55:10: error: ‘__builtin_isnormal’ is not a member of ‘std’
     if (!std::isnormal(d)) {
          ^
/home/aensley/xmrig-nvidia/src/api/ApiState.cpp:55:10: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnormal’
CMakeFiles/xmrig-nvidia.dir/build.make:86: recipe for target 'CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by aensley** [comment]
_Replying to https://github.com/xmrig/xmrig-nvidia/issues/36#issuecomment-344597931 by @mattWhitwam:_

This worked! However, my GUI is unresponsive while the miner runs even on lowest possible thread/block settings. New problem, but I'm closer!

**Comment by aensley** [comment]
Solved. Just had to tune bfactor and bsleep a little. Running great now with the `isnormal` hack.

**Comment by aensley** [comment]
Here's a one-liner that fixes it when run from the source directory:

```
grep -rl --include="*.cpp" "std::isnormal" | xargs sed -i 's/std::isnormal/isnormal/g'
```

**Comment by vibhas77** [comment]
Hi, I encountered a simialr problem while compiling the CUDA 8 build directions. Replacing std::isnormal with just isnormal worked wonders for me.

Thanks for reporting this issue.

**Comment by xmrig** [comment]
Strange, same code works without issues in CPU miner, at least no one report it.
Anyway I replaced `std::isnormal` to `isnormal`.
Thanks you all.

**Comment by matiasinsaurralde** [comment]
I'm getting this:
```
[  6%] Built target xmrig-cuda
Scanning dependencies of target xmrig-nvidia
[  9%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o
/tmp/xmrig-nvidia/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/tmp/xmrig-nvidia/src/api/ApiState.cpp:154:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
                                                     ^
/tmp/xmrig-nvidia/src/api/ApiState.cpp:161:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^
/tmp/xmrig-nvidia/src/api/ApiState.cpp:165:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^
CMakeFiles/xmrig-nvidia.dir/build.make:86: recipe for target 'CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by matiasinsaurralde** [comment]
Updating to `libuv1` solved the issue 👍

**Comment by howTOdoIT2** [comment]
can you share the ubuntu version  compile file?

**Comment by George33** [comment]
Noob here...  I'm doing this with xmrrig-amd and xubuntu 17.01.  

I used the "std::isnormal" to "normal" trick and got the build to:
 
```
[100%] Linking CXX executable xmrig-amd
[100%] Built target xmrig-amd
```  

The green colored xmrig-amd file now shows up in the directory but when I type  **xmrig-amd** on the command line  it says "command not found".   Am I missing something obvious here?

**Comment by mattWhitwam** [comment]
Try: ./xmrig-amd

**Comment by xmrig** [comment]
Already fixed.
